---
title: "geomeTriD Vignette: plot single cells in 3d"
author: "Jianhong Ou"
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('geomeTriD')`"
abstract: >
  Visualize single cell RNA-seq data in 3D plots.
vignette: >
  %\VignetteIndexEntry{geomeTriD Vignette: plot single cell data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  html_document:
    theme: simplex
    toc: true
    toc_float: true
    toc_depth: 4
    fig_caption: true
---

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(geomeTriD)
  library(rgl)
  library(manipulateWidget)
})
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

# Introduction

`geomeTriD` can be used to view data in 3D. Here we will show how to use it 
to plot the single cell data in 3D.

# Installation

```{r installation, eval=FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("jianhong/geomeTriD")
```


# Plot single cell data

The input data should be a data.frame with x,y,z coordinates.

```{r}
library(geomeTriD)
cells <- readRDS(system.file('extdata', 'pbmc_small.3d.rds',
                             package='geomeTriD'))
head(cells)
## color the cells by 'groups' info
objs <- view3dCells(cells, x="umap_1", y="umap_2", z="umap_3",
                    color = 'groups',
                    colorFun = function(x){
                      ifelse(x=='g1', 'red', 'blue')
                    },
                    renderer='none')
```

Plot the cells by `rgl`.
```{r mdsPlot3d}
library(manipulateWidget)
clear3d() # Remove the earlier display
rglViewer(objs, background = 'white')
rglwidget()
```

Plot it by `threeJs`.
```{r threejs}
threeJsViewer(objs)
```

We can also try to color the cells by a numeric column.
```{r}
view3dCells(cells, x="umap_1", y="umap_2", z="umap_3",
            color = 'nCount_RNA',
            colorFun = function(x, pal=colorRampPalette(c('black', 'red'))(5)){
                          limits=range(x)
                          pal[findInterval(x, seq(limits[1], limits[2], 
                                                  length.out=length(pal)+1),
                                           all.inside=TRUE)]
                        },
            renderer = 'threejs')
```


# Session Info
```{r sessionInfo, results='asis'}
sessionInfo()
```

